import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ojos de Cielo Arte",
  description: "Generated by Alejandro Ponce",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}><Nav />{children}</body>
    </html>
  );
}
